### ISSUE TITLE
[Bug]: No settings available

### ISSUE THREAD

**Issue by AlfaSierra92** [luisbocanegra/plasma-intel-gpu-monitor#10]
No settings are available when I try to configure this applet; right click on the applet open an empty window.
General tab doesn't work.
![image](https://github.com/user-attachments/assets/ff711a0a-9092-4e4e-9ead-16547ec3d006)
I'm on Ubuntu 24.10 with Kde 6 installed.
![image](https://github.com/user-attachments/assets/54d57f61-1a91-4510-92cb-0b6454e258d6)

**Comment by luisbocanegra** [comment]
Run `journalctl -f` then open the widget settings window and paste the printed output here.

**Comment by AlfaSierra92** [comment]
`nov 06 16:48:35 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: QQmlComponent: Component is not ready`
`nov 06 16:48:35 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: file:///usr/lib/x86_64-linux-gnu/qt6/qml/org/kde/kirigami/PageRow.qml:1078: Error: Error while loading page: file:///home/antonio/.local/share/plasma/plasmoids/luisbocanegra.intel.gpu.monitor/contents/ui/configGeneral.qml:4 module "Qt.labs.settings" is not installed`
`nov 06 16:48:36 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: QQmlComponent: Component is not ready`
`nov 06 16:48:36 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: file:///usr/lib/x86_64-linux-gnu/qt6/qml/org/kde/kirigami/PageRow.qml:1078: Error: Error while loading page: file:///home/antonio/.local/share/plasma/plasmoids/luisbocanegra.intel.gpu.monitor/contents/ui/configGeneral.qml:4 module "Qt.labs.settings" is not installed`
`nov 06 16:48:37 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: QQmlComponent: Component is not ready`
`nov 06 16:48:37 antonio-VivoBook-ASUSLaptop-X531FL-S531FL plasmashell[3220]: file:///usr/lib/x86_64-linux-gnu/qt6/qml/org/kde/kirigami/PageRow.qml:1078: Error: Error while loading page: file:///home/antonio/.local/share/plasma/plasmoids/luisbocanegra.intel.gpu.monitor/contents/ui/configGeneral.qml:4 module "Qt.labs.settings" is not installed`
`

**Comment by luisbocanegra** [comment]
It's a missing dependency but is not being used by this widget and I forgot to remove it 🤦‍♂️

> module "Qt.labs.settings" is not installed

There are also other imports that are not needed, I will remove them and let you know when I have a version to test.

**Comment by luisbocanegra** [comment]
Hi, version [0.3.1](https://github.com/luisbocanegra/plasma-intel-gpu-monitor/releases/tag/v0.3.1) should fix this, can you update the widget and let me know if it works?

**Comment by AlfaSierra92** [comment]
Working fine! Thank you!
