### ISSUE TITLE
Modify kernel.perf_event_paranoid parameter

### ISSUE THREAD

**Issue by AlfaSierra92** [luisbocanegra/plasma-intel-gpu-monitor#2]
In some distros such as Ubuntu, you have to set also the kernel.perf_event_paranoid parameter to 0 by the command sysctl or editing the sysctl.conf file; otherwise intel_gpu_tools cannot be executed with no sudo. Could you adding it to the readme file? Anyway, thanks for this work!

**Comment by luisbocanegra** [comment]
Even after enabling the systemd unit (or running `sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top`)? 

According to the [docs](https://www.kernel.org/doc/Documentation/admin-guide/perf-security.rst) setting `CAP_PERFMON` (privileged process) should be enough and more secure than setting `/proc/sys/kernel/perf_event_paranoid` to -1 or 0 (system wide), and at least on Arch the default value is 2.

Are there any errors when running `intel_gpu_top` from terminal without sudo?

**Comment by AlfaSierra92** [comment]
Seems that on Ubuntu the default value is 4 so `intel_gpu_top` doesn't running without sudo

**Comment by luisbocanegra** [comment]
So looks like current Ubuntu (and maybe Debian too) have [extra paranoia levels, 4 and possibly 3 for some old versions(?)](https://askubuntu.com/questions/1400874/what-does-perf-paranoia-level-four-do):

 perf event paranoia level:
 -1 - not paranoid at all
 0 - disallow raw tracepoint access for unpriv
 1 - disallow cpu events for unpriv
 2 - disallow kernel profiling for unpriv
 3 - was either same as 2 or 4 in older kernels? https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/tree/kernel/events/core.c
 4 - disallow all unpriv perf event use

So if you set it to 2 it works, right? If so there's no need to go lower.

If that's the case I think it would be better to recommend setting it to 2 as most distros should support that value and is the default in the kernel.

**Comment by AlfaSierra92** [comment]
Yes, settings it to 2 seems working fine

**Comment by luisbocanegra** [comment]
Thanks, I will add it to the README

**Comment by luisbocanegra** [comment]
BTW, which GPU(s) do you have in your system?

**Comment by AlfaSierra92** [comment]
> BTW, which GPU(s) do you have in your system?

Intel UHD620

**Comment by luisbocanegra** [comment]
Done in https://github.com/luisbocanegra/plasma-intel-gpu-monitor/commit/ea05c40c86279260c0128f0eb322a8da3c4ae6c8 thanks for the feedback
