### ISSUE TITLE
intel-gpu-monitor  not detecting gpu

### ISSUE THREAD

**Issue by hackerghost607** [luisbocanegra/plasma-intel-gpu-monitor#3]
i installed intel-gpu-monitor  on Kali GNU/Linux Rolling x86_64 and its not detecting the gpu 
![Uploading Screenshot_20231201_135627.png…]()

**Comment by luisbocanegra** [comment]
Looks like your image didn't upload correctly, I can't open it.

Please share the output of this command, it will list your card(s) and try to run intel_gpu_top on them.

```
intel_gpu_top -L | tee /dev/stderr | awk '/^card/ {print $1}' | while read card; do echo "\n$card:"; timeout .4 intel_gpu_top -d drm:/dev/dri/$card -J -s 500; done
```
