### ISSUE TITLE
Error reporting causes the taskbar and launcher to freeze

### ISSUE THREAD

**Issue by LuorixDev** [luisbocanegra/plasma-intel-gpu-monitor#5]
I noticed that there is the same error as another issue in the background, and it causes the taskbar to be completely stuck when the computer load is high, and it takes more than 2 seconds to respond after clicking.

**Comment by luisbocanegra** [comment]
What other issue, this one https://github.com/luisbocanegra/plasma-intel-gpu-monitor/issues/4 ? 
Which gpu do you have, are any stats shown at all? Please share the output of `journalctl -f` when the widget is running

Also share the output of this command, it will list your card(s) and try to run intel_gpu_top on them.

```
intel_gpu_top -L | tee /dev/stderr | awk '/^card/ {print $1}' | while read card; do echo "\n$card:"; timeout .4 intel_gpu_top -d drm:/dev/dri/$card -J -s 500; done
```
