### ISSUE TITLE
[FEATURE REQUEST] GPU usage on the widget icon

### ISSUE THREAD

**Issue by Damglador** [luisbocanegra/plasma-intel-gpu-monitor#6]
Ability to show usage percentage on widget in a panel.

I have a bunch of resource monitors on my top panel, but with Plasma tools it isn't possible to show either percentage or graph of intel iGPU usage. 

![зображення](https://github.com/user-attachments/assets/a9537877-9c61-4285-9291-825c3a8e8aa4)

Would be very handy to see at least just iGPU usage percentage on the widget, so it's not required to have the whole widget menu being open to monitor GPU usage.

**Comment by luisbocanegra** [comment]
Thanks for your feedback, I will add this for the next version.

**Comment by luisbocanegra** [comment]
This is now available in version https://github.com/luisbocanegra/plasma-intel-gpu-monitor/releases/tag/v0.3.0

![Screenshot_20241020_002121](https://github.com/user-attachments/assets/3f396878-3798-453f-a6cf-67db9693c8d4)


![append-2024-10-20-002019](https://github.com/user-attachments/assets/197d5ad2-c78e-4abf-b4f6-f88b984b8388)
